# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CitceaProbabilityAnalysis
                                 A QGIS plugin
 CITCEA Probability analysis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-02-19
        git sha              : $Format:%H$
        copyright            : (C) 2024 by MMP
        email                : montserrat.montala@upc.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.core import QgsProject, NULL
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.PyQt.QtCore import * #QSettings, QTranslator, QCoreApplication, QVariant
from qgis.PyQt.QtGui import * #QIcon, QColor
from qgis.PyQt.QtWidgets import QAction
from qgis.core import * #QgsProject, Qgis, QgsLayerTreeGroup, QgsLayerTreeLayer, QgsField, QgsPoint, QgsFields, QgsWkbTypes, QgsFeature, QgsVectorLayer, QgsExpression, QgsGeometry, QgsSpatialIndex, QgsRectangle, QgsMapClippingRegion, NULL  #modified 18/12/2023
from pathlib import Path

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .CITCEA_Probability_analysis_dialog import CitceaProbabilityAnalysisDialog
import os.path
import math
import qgis.utils
import processing 


class CitceaProbabilityAnalysis:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'CitceaProbabilityAnalysis_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&CITCEA Probability analysis')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('CitceaProbabilityAnalysis', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/CITCEA_Probability_analysis/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'CITCEA Probability analysis'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&CITCEA Probability analysis'),
                action)
            self.iface.removeToolBarIcon(action)

    def comboBox_control(self, index):
        if index != 2:
            self.dlg.lineEdit.setEnabled(False)
            self.dlg.lineEdit_2.setEnabled(False)
            self.dlg.lineEdit_3.setEnabled(False)
            self.dlg.lineEdit_4.setEnabled(False)           
        else:
            self.dlg.lineEdit.setEnabled(True)
            self.dlg.lineEdit_2.setEnabled(True)
            self.dlg.lineEdit_3.setEnabled(True)
            self.dlg.lineEdit_4.setEnabled(True)
            
            
        
    
    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = CitceaProbabilityAnalysisDialog()
            
        # Input all hazards
        events = ['','INDEPENDENT EVENTS', 'DEPENDENT EVENTS']
        hazards = QgsProject.instance().layerTreeRoot().findGroup('Hazards').children() 
                       
        # Clear the contents of the comboBox from previous runs
        self.dlg.comboBox.clear()
        self.dlg.comboBox_2.clear()
        self.dlg.comboBox_3.clear()
        
        # Provides all potential case studies to be selected 
        self.dlg.comboBox.addItems(events) 
        self.dlg.comboBox_2.addItems([hazard.name() for hazard in hazards])
        self.dlg.comboBox_3.addItems([hazard.name() for hazard in hazards])  
        
        self.dlg.comboBox.currentIndexChanged.connect(self.comboBox_control)
        
               
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
        
            Type_event = self.dlg.comboBox.currentText()
            Layer_event_A_Index = self.dlg.comboBox_2.currentIndex()
            Layer_event_B_Index = self.dlg.comboBox_3.currentIndex()
            
            if  Type_event == 'DEPENDENT EVENTS':
                Probab_B_when_A_summer = float(self.dlg.lineEdit.text())
                Probab_B_when_A_winter = float(self.dlg.lineEdit_2.text())
                Probab_B_when_A_autumn = float(self.dlg.lineEdit_3.text())
                Probab_B_when_A_spring = float(self.dlg.lineEdit_4.text())
            else: 
                Probab_B_when_A_summer = 0
                Probab_B_when_A_winter = 0
                Probab_B_when_A_autumn = 0
                Probab_B_when_A_spring = 0
                                               
            Layer_event_A = hazards[Layer_event_A_Index].layer()
            Layer_event_B = hazards[Layer_event_B_Index].layer()
            
            #1 Create a new layer
            name_layer_A = Layer_event_A.name()
            name_layer_B = Layer_event_B.name()
            
            new_lay_A_B = QgsVectorLayer('polygon?crs=EPSG:25831&field=id:string',str(name_layer_A)+'-'+str(name_layer_B),'memory')
            new_lay_A_B.startEditing() 
            
            #2 Create one field per season 
            seasons_name = ['WINTER','SUMMER','SPRING','AUTUMN']
            Probab_B_when_A = [0, Probab_B_when_A_winter, Probab_B_when_A_summer, Probab_B_when_A_spring, Probab_B_when_A_autumn]
            seasons = [QgsField((str(seasons_name[0])), QVariant.Double),QgsField((str(seasons_name[1])), QVariant.Double),QgsField((str(seasons_name[2])), QVariant.Double),QgsField((str(seasons_name[3])), QVariant.Double)]
            new_lay_A_B.dataProvider().addAttributes(seasons)
            new_lay_A_B.updateFields()   
                          
            
            #3 Create the new layers: geoemtries + P(A&B)
            fields = new_lay_A_B.dataProvider().fields()
            fields_names = new_lay_A_B.dataProvider().fields().names()
            feature = QgsFeature()
            feature.setFields(fields)
            a = 0
            b = 0
            
            for feat_layer_A in Layer_event_A.getFeatures():
                for feat_layer_B in Layer_event_B.getFeatures():
                    if feat_layer_A.geometry().intersects(feat_layer_B.geometry()):
                        a = a + 1 
                        new_geometry = feat_layer_A.geometry().intersection(feat_layer_B.geometry())
                        feature.setGeometry(new_geometry)
                        q = fields.indexFromName('id')
                        feature[q] = 'zone_'+str(a)
                        for s in range(len(fields_names)):
                            if s > 0:
                                if str(Type_event) == 'INDEPENDENT EVENTS':    
                                    feature[s] = feat_layer_A[str(fields_names[s])] * feat_layer_B[str(fields_names[s])]
                                elif str(Type_event) == 'DEPENDENT EVENTS': 
                                    feature[s] = Probab_B_when_A[s] * feat_layer_A[str(fields_names[s])] * feat_layer_B[str(fields_names[s])]
                                else: 
                                    self.iface.messageBar().pushMessage("Error","Please, identify the kind of events", level=Qgis.Critical, duration=0)
                        new_lay_A_B.dataProvider().addFeature(feature)            
            
            new_lay_A_B.updateExtents()
            new_lay_A_B.commitChanges()

            #4 Import on map 
            
            QgsProject.instance().addMapLayer(new_lay_A_B)
                                
            
            pass
