# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HazardIden
                                 A QGIS plugin
 Natural hazards indentification for resiliency analysis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-12-12
        copyright            : (C) 2023 by MMP
        email                : montserrat.montala@upc.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HazardIden class from file HazardIden.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Hazards_Identification import HazardIden
    return HazardIden(iface)
