# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HazardIden
                                 A QGIS plugin
 Natural hazards indentification for resiliency analysis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-12-12
        git sha              : $Format:%H$
        copyright            : (C) 2023 by MMP
        email                : montserrat.montala@upc.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.core import QgsProject, NULL
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.PyQt.QtCore import * 
from qgis.PyQt.QtGui import * 
from qgis.PyQt.QtWidgets import QAction
from qgis.core import * 
from pathlib import Path

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .Hazards_Identification_dialog import HazardIdenDialog
import os.path
import math
import qgis.utils
import processing 


class HazardIden:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'HazardIden_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Resilience: Risk Assessment')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('HazardIden', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/Hazards_Identification/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'CITCEA Resilience'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Resilience: Risk Assessment'),
                action)
            self.iface.removeToolBarIcon(action)
            
    def select_output_file(self):
        filename, _filter = QFileDialog.getSaveFileName(self.dlg, "Select output file ","", '*.csv')
        self.dlg.lineEdit_4.setText(filename)
    
    def open_file_dialog_1(self):
        filename, ok =QFileDialog.getOpenFileName(self.dlg, "Select a file ","", '*.csv');
        if filename: 
            path = Path(filename)
            self.dlg.lineEdit_3.setText(str(path))
            
    def open_file_dialog_2(self):
        filename, ok =QFileDialog.getOpenFileName(self.dlg, "Select a file ","", '*.csv');
        if filename: 
            path = Path(filename)
            self.dlg.lineEdit.setText(str(path))

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = HazardIdenDialog()
        # Fetch the currently loaded layers
       
        # Inputs all potential case studies
        layers = QgsProject.instance().layerTreeRoot().findGroup('System_TBA').children()
        seasons = ['','WINTER', 'SUMMER', 'SPRING', 'AUTUMN']
        
        # The childs of the Layers_withHazards are added.
        root = QgsProject.instance().layerTreeRoot().findGroup('Hazards')
        hazards = QgsProject.instance().layerTreeRoot().findGroup('Hazards').children()  
        
        # A list w/ the hazards names is created
        n = 0                                                                                       #added 15/12/2023
        hazards_names = []                                                                          #added 15/12/2023         
        for child in root.children():                                                               #added 15/12/2023
            if isinstance(child, QgsLayerTreeLayer):                                                #added 15/12/2023
                n = n + 1                                                                           #added 15/12/2023
                hazards_names.append(child.name())                                                  #added 15/12/2023
        
                           
        
        # Clear the contents of the comboBox from previous runs
        self.dlg.comboBox.clear()
        self.dlg.comboBox_2.clear()
        # Provides all potential case studies to be selected 
        self.dlg.comboBox.addItems([layer.name() for layer in layers])
        self.dlg.comboBox_2.addItems([layer.name() for layer in layers])
        self.dlg.comboBox_3.addItems(seasons)
        self.dlg.pushButton_3.clicked.connect(self.select_output_file)
        self.dlg.pushButton_2.clicked.connect(self.open_file_dialog_1)
        self.dlg.pushButton.clicked.connect(self.open_file_dialog_2)
        
        # Opens de dialog BOX in QGIS
        self.dlg.show()
        # When "Acceptar" the model starts
        result = self.dlg.exec_()
        # See if OK/ "Acceptar" was pressed
        if result:
            
            selectedLayerIndex_1 = self.dlg.comboBox.currentIndex()     #revisar esta línia de codigo, repetida en 266
            selectedLayerIndex_2 = self.dlg.comboBox_2.currentIndex()   #revisar esta línia de codigo, repetida en 267
                        
            filename = self.dlg.lineEdit_4.text()
            distance = float(self.dlg.lineEdit_2.text())
            energy = float(self.dlg.lineEdit_5.text())
            season = self.dlg.comboBox_3.currentText()
            buses_vul = self.dlg.lineEdit_3.text()
            uri_buses = 'file:///'+str(buses_vul)+'?delimiter=%s' % (";")
            power_lines_vul = self.dlg.lineEdit.text()
            uri_power_lines = 'file:///'+str(power_lines_vul)+'?delimiter=%s' % (";")
            
            with open(filename, 'w') as output_file:
            
                # Takes the layers of the selected case studies selected by the user
                # selectedLayerIndex_1 = self.dlg.comboBox.currentIndex()
                # selectedLayerIndex_2 = self.dlg.comboBox_2.currentIndex()
                selectedLayer_1 = layers[selectedLayerIndex_1].layer()
                selectedLayer_2 = layers[selectedLayerIndex_2].layer()
                features_num = selectedLayer_1.featureCount() + selectedLayer_1.featureCount()
                hazards_num = n
                
                ##### IDENTIFY AND PLOT VULNERABILITIES 
                # Buses 
                lyr_buses_vul = QgsVectorLayer(uri_buses, 'Buses Vulnerabilities','delimitedtext')                  
                QgsProject.instance().addMapLayer(lyr_buses_vul)
                # Power Lines
                lyr_powerlines_vul = QgsVectorLayer(uri_power_lines, 'Power Lines Vulnerabilities','delimitedtext')
                QgsProject.instance().addMapLayer(lyr_powerlines_vul)
                
                ##### CREATE NEW LAYERS             
                # SUBSTATIONS
                #1 Identify the type of input layer                
                layer_type_sub = selectedLayer_1.wkbType()
                
                #2 Identify the fields for case study
                fields_sub = selectedLayer_1.dataProvider().fields().toList()  
                field_sub_names = selectedLayer_1.fields().names()
                
                #3 Create a new layer same type than input layer 
                newLayer_sub = QgsVectorLayer(QgsWkbTypes.displayString(layer_type_sub)+'?crs=EPSG:25831','Substations','memory')
                newLayer_sub.startEditing()                           
                
                #4 Create fields in new layer                            
                newLayer_sub.dataProvider().addAttributes(fields_sub)
                newLayer_sub.updateFields()
                
                #5 Import attributes from case study in new layer                                 
                feature_sub = QgsFeature()  
                feature_sub.setAttributes(fields_sub)                
                
                for sb in selectedLayer_1.getFeatures():
                    geom = sb.geometry()
                    feature_sub.setGeometry(geom)
                    feature_sub  = sb
                    newLayer_sub.dataProvider().addFeature(feature_sub)
                newLayer_sub.updateExtents()
                newLayer_sub.commitChanges()
                
                newLayer_sub.dataProvider().addAttributes([QgsField(('Total_risk'), QVariant.Double)])                                 
                newLayer_sub.updateFields() 
                for sl in newLayer_sub.getFeatures():
                        sl['Total_risk'] = 0
                        newLayer_sub.updateFeature(sl)
                              
                               
                # POWER LINES
                #1 Identify the type of input layer
                layer_type = selectedLayer_2.wkbType()
                
                #2 Identify the fields for case study and add two fields for the risk analysis          
                fields = selectedLayer_2.dataProvider().fields() 
                fields_cs_name = selectedLayer_2.dataProvider().fields().names() 
                field_new_name = QgsField('Line_Name_Seg', QVariant.String)
                fields.append(field_new_name)
                field_segment_frac = QgsField('Per_TotLen', QVariant.Double )
                fields.append(field_segment_frac)
                field_tot_risk = QgsField(('Total_risk'), QVariant.Double)
                fields.append(field_tot_risk)
                                                                
                #3 Create a new layer same type than input layer 
                newLayer_PL = QgsVectorLayer(QgsWkbTypes.displayString(layer_type)+'?crs=EPSG:25831','Power_Lines_Segments','memory')
                newLayer_PL.startEditing()                
                              
                #4 Create fields in new layer                              
                newLayer_PL.dataProvider().addAttributes(fields)
                newLayer_PL.updateFields()
                
                #5 Import attributes from case study in new layer                                  
                feature = QgsFeature()                
                feature.setFields(fields)
                                
                for x in selectedLayer_2.getFeatures():
                    i = 1
                    geom = x.geometry() 
                    # Divide the geometry in equal segments 
                    for line in geom.parts():
                        a = x['Line_Name']
                        linepartgeom = QgsGeometry.fromPolyline(line)
                        partlength = linepartgeom.length()
                        nsegments = math.ceil(partlength / distance)
                        startdist = 0
                        enddist = distance
                        # Add the segments geometry in the internal_auxiliar QgsFeature & in the QgsVectorLayer
                        for segment in range(0,nsegments):
                            segmentlinestring = line.curveSubstring(startdist,enddist)
                            segmentgeom = QgsGeometry.fromPolyline(segmentlinestring)
                            feature.setGeometry(segmentgeom)
                            for p in range(len(fields_cs_name)):
                                feature[p] = x[str(fields_cs_name[p])]
                            q = fields.indexFromName('Line_Name_Seg')
                            w = fields.indexFromName('Per_TotLen')
                            y = fields.indexFromName('Total_risk')
                            feature[q] = str(a)+'_Seg_'+str(i)
                            feature[w] = segmentgeom.length() / partlength
                            feature[y] = 0
                            newLayer_PL.dataProvider().addFeature(feature)                           
                            startdist = startdist + distance
                            enddist = enddist + distance
                            i = i + 1
                         
                newLayer_PL.updateExtents()
                newLayer_PL.commitChanges()
                
                
                #Calculate with the new layers
                
                selectedLayer_1 = newLayer_sub
                selectedLayer_2 = newLayer_PL
                
                QgsProject.instance().addMapLayer(newLayer_sub) 
                QgsProject.instance().addMapLayer(newLayer_PL) 
                                
                               
                ext_1 = selectedLayer_1.extent()                                                                                    #added 18/12/2020 - MMP: creates the extent of buses
                ext_2 = selectedLayer_2.extent()                                                                                    #added 18/12/2020 - MMP: creates the extent of power lines
                ext_1.combineExtentWith(ext_2)                                                                                      #added 18/12/2020 - MMP: combine both extents
                
                ######## ADD VULNERABILITIES #####
                ## Buses
                joinField = 'Name'
                targetField = 'Name'
                                              
                results = processing.run("native:joinattributestable", {'INPUT':selectedLayer_1,'FIELD':targetField,'INPUT_2':lyr_buses_vul,'FIELD_2':joinField,'FIELDS_TO_COPY':[],'METHOD':0,'DISCARD_NONMATCHING':False,'PREFIX':'','OUTPUT': 'TEMPORARY_OUTPUT'})
                results = results['OUTPUT']
                results_2 = processing.run("native:deletecolumn", {'INPUT': results,'COLUMN':['Name_2'],'OUTPUT':'TEMPORARY_OUTPUT'})
                selectedLayer_1 = results_2['OUTPUT']
                selectedLayer_1.setName('Substations')
                selectedLayer_1_names = selectedLayer_1.fields().names()
                selectedLayer_1.startEditing()
                for i in range(len(selectedLayer_1_names)):
                    for sl in selectedLayer_1.getFeatures():
                        if sl[str(selectedLayer_1_names[i])] == NULL:
                            sl[str(selectedLayer_1_names[i])] = 0
                            selectedLayer_1.updateFeature(sl)                               
                
                ## Power Lines
                joinField = 'Line_Name'
                targetField = 'Line_Name'
                results = processing.run("native:joinattributestable", {'INPUT':selectedLayer_2,'FIELD':targetField,'INPUT_2':lyr_powerlines_vul,'FIELD_2':joinField,'FIELDS_TO_COPY':[],'METHOD':0,'DISCARD_NONMATCHING':False,'PREFIX':'','OUTPUT': 'TEMPORARY_OUTPUT'})
                results = results['OUTPUT']
                results_2 = processing.run("native:deletecolumn", {'INPUT': results,'COLUMN':['Name'],'OUTPUT':'TEMPORARY_OUTPUT'})
                selectedLayer_2 = results_2['OUTPUT']
                selectedLayer_2.setName('Power Lines')
                selectedLayer_2_names = selectedLayer_2.fields().names()
                selectedLayer_2.startEditing()
                for i in range(len(selectedLayer_2_names)):
                    for sl in selectedLayer_2.getFeatures():
                        if sl[str(selectedLayer_2_names[i])] == NULL:
                            sl[str(selectedLayer_2_names[i])] = 0
                            selectedLayer_2.updateFeature(sl) 
                            
                i = -1
                for child in root.children():                                                                                       #added 15/12/2023 - MMP: select one hazard to analyze
                    i = i + 1
                    
                    pr = selectedLayer_1.dataProvider()                                                                             #added 15/12/2023
                    pr.addAttributes([QgsField(str(hazards_names[i]), QVariant.Double)])                                            #added 15/12/2023 - MMP: add a field for each hazard
                    selectedLayer_1.updateFields()                                                                                  #added 15/12/2023 - MMP: update the fields to include the added fields
                    for sl in selectedLayer_1.getFeatures():
                        sl[str(hazards_names[i])] = 0
                        selectedLayer_1.updateFeature(sl)
                                                            
                    pr = selectedLayer_2.dataProvider()                                                                             #added 15/12/2023
                    pr.addAttributes([QgsField(str(hazards_names[i]), QVariant.Double)])                                            #added 18/12/2023 - MMP: add a field for each hazard
                    selectedLayer_2.updateFields()                                                                                  #added 18/12/2023 - MMP: update the fields to include the added fields
                    for sl in selectedLayer_2.getFeatures():
                        sl[str(hazards_names[i])] = 0
                        selectedLayer_2.updateFeature(sl)
                                                          
                    # for sl in selectedLayer_2.getFeatures():   ## comentat 23/01/2025
                        # sl[str(hazards_names[i])] = 0
                        # selectedLayer_2.updateFeature(sl)
                    
                    if isinstance(child, QgsLayerTreeLayer):                                                                                                                                                                                #added 18/12/2023
                        hzr_lay =  child.layer()                                                                                                                                                                                            #added 18/12/2023 - MMP: take a layer of the hazards   
                        for a in hzr_lay.getFeatures(ext_1):                                                                                                                                                                                #added 18/12/2023 - MMP: obtained the features (geometry) of the layer
                            for f in selectedLayer_1.getFeatures():                                                                                                                                                                         #added 18/12/2023 - MMP: obtain the features (goemetry) of the case study                      
                                if a.geometry().intersects(f.geometry()):                                                                                                                                                                   #added 18/12/2023 - MMP: compare the geometry of the selected hazard w/ the geometry of the case study 
                                    if a[str(season)] > f[str(hazards_names[i])]:
                                        f[str(hazards_names[i])] = a[str(season)]                                                                                                                                                           #added 18/12/2023 - MMP: return 'YES' if both layers intersect
                                    else:
                                        f[str(hazards_names[i])] = f[str(hazards_names[i])]                                                                                                                                                 #added 18/12/2023 - MMP: return 'YES' if both layers intersect
                                    # f['Total_risk'] = f['Total_risk'] + f[str(hazards_names[i])]*f[str(hazards_names[i]+'_likelihood')]*f[str(hazards_names[i]+'_damage')]                                                                  # Aquest risc total es calcula com la suma dels riscs 
                                    selectedLayer_1.updateFeature(f)                                                                                                                                                                        #added 18/12/2023 - MMP: update the features
                            for g in selectedLayer_2.getFeatures():                                                                                                                                                                         #added 18/12/2023 - MMP: obtain the features (goemetry) of the case study
                                if a.geometry().intersects(g.geometry()):                                                                                                                                                                   #added 18/12/2023 - MMP: compare the geometry of the selected hazard w/ the geometry of the case study
                                    if a[str(season)] > g[str(hazards_names[i])]:
                                        g[str(hazards_names[i])] = a[str(season)]                                                                                                                                                           #added 18/12/2023 - MMP: return 'YES' if both layers intersect
                                    else:
                                        g[str(hazards_names[i])] = g[str(hazards_names[i])] 
                                    selectedLayer_2.updateFeature(g)   
                        
                        # Following two loops added 24/01 to minimize the problems in case of intersecting in more than one part
                        
                        for f in selectedLayer_1.getFeatures(): 
                            f['Total_risk'] = f['Total_risk'] + f[str(hazards_names[i])]*f[str(hazards_names[i]+'_likelihood')]*f[str(hazards_names[i]+'_damage')]                                                                  # Aquest risc total es calcula com la suma dels riscs 
                            selectedLayer_1.updateFeature(f)
                    
                        for g in selectedLayer_2.getFeatures():
                            g['Total_risk'] = g['Total_risk'] + g[str(hazards_names[i])]*g[str(hazards_names[i]+'_likelihood')]*g[str(hazards_names[i]+'_damage')] *g['Per_TotLen']                                                  # Aquest risc total es calcula com la suma dels riscs
                            selectedLayer_2.updateFeature(g)      
                    
                                              
                ##### CLEANING RESULTS ####
                # Buses
                # Join attributes thorugh location
                Sum_TotalRisk = processing.run("qgis:joinbylocationsummary", {'INPUT': selectedLayer_1,'PREDICATE':[2],'JOIN':selectedLayer_1,'JOIN_FIELDS':['Total_risk'],'SUMMARIES':[5],'DISCARD_NONMATCHING':False,'OUTPUT':'TEMPORARY_OUTPUT'})
                Sum_TotalRisk = Sum_TotalRisk['OUTPUT']
                
                # Remove duplicated geometries
                selectedLayer_1_plot = processing.run("native:deleteduplicategeometries", {'INPUT':Sum_TotalRisk,'OUTPUT':'TEMPORARY_OUTPUT'})
                selectedLayer_1_plot = selectedLayer_1_plot['OUTPUT'] 
                
                # Keep only the RISK field 
                selectedLayer_1_plot = processing.run("native:retainfields", {'INPUT':selectedLayer_1_plot,'FIELDS':['Name','Total_risk_sum'],'OUTPUT':'TEMPORARY_OUTPUT'})
                selectedLayer_1_plot = selectedLayer_1_plot['OUTPUT'] 
                selectedLayer_1_plot = processing.run("native:renametablefield", {'INPUT': selectedLayer_1_plot,'FIELD':'Total_risk_sum','NEW_NAME':'RISK (kWh)','OUTPUT':'TEMPORARY_OUTPUT'})
                selectedLayer_1_plot = selectedLayer_1_plot['OUTPUT'] 
                
                selectedLayer_1_plot.setName('Substations')
                
                # Power Lines
                # Join attributes thorugh location            
                               
                               
                # Create a new empty layer for the buffered features (selectlayer_3)
                selectLayer_3 = QgsVectorLayer('Polygon?crs=' + selectedLayer_2.crs().toWkt(), 'selectLayer_3', 'memory')
                provider = selectLayer_3.dataProvider()

                # Create the fields for selectlayer_3, copy them from selectlayer_2
                provider.addAttributes(selectedLayer_2.fields())
                selectLayer_3.updateFields()

                # Iterate over the selected features from selectlayer_2
                for feature in selectedLayer_2.getFeatures():
                    # Create a buffer of each feature (buffer size can be adjusted, e.g., 100 units)
                    buffer = feature.geometry().buffer(100, 5)  # 100 units buffer, with 5 segments per quarter circle
                    # Create a new feature with the buffer geometry
                    buffer_feature = QgsFeature()
                    buffer_feature.setGeometry(buffer)
                    buffer_feature.setAttributes(feature.attributes())
                    
                    # Add the buffered feature to selectlayer_3
                    provider.addFeature(buffer_feature)
                        
                                        
                Sum_TotalRisk_PL = processing.run("qgis:joinbylocationsummary", {'INPUT': selectedLayer_2,'PREDICATE':[5],'JOIN':selectLayer_3,'JOIN_FIELDS':['Total_risk'],'SUMMARIES':[5],'DISCARD_NONMATCHING':False,'OUTPUT':'TEMPORARY_OUTPUT'})
                Sum_TotalRisk_PL = Sum_TotalRisk_PL['OUTPUT']   

                ### POSSIBLE ERROR AQUÍ"
                               
                # Remove duplicated geometries
                selectedLayer_2_plot = processing.run("native:deleteduplicategeometries", {'INPUT':Sum_TotalRisk_PL,'OUTPUT':'TEMPORARY_OUTPUT'})
                selectedLayer_2_plot = selectedLayer_2_plot['OUTPUT'] 
                
                # Keep only the RISK field 
                selectedLayer_2_plot = processing.run("native:retainfields", {'INPUT':selectedLayer_2_plot,'FIELDS':['Line_Name_Seg','Total_risk_sum'],'OUTPUT':'TEMPORARY_OUTPUT'})
                selectedLayer_2_plot = selectedLayer_2_plot['OUTPUT'] 
                selectedLayer_2_plot = processing.run("native:renametablefield", {'INPUT': selectedLayer_2_plot,'FIELD':'Total_risk_sum','NEW_NAME':'RISK (kWh)','OUTPUT':'TEMPORARY_OUTPUT'})
                selectedLayer_2_plot = selectedLayer_2_plot['OUTPUT'] 
                
                selectedLayer_2_plot.setName('Power Lines')
                
                
                ###############              
                
                
                
                ######### PLOT ####
                
                QgsProject.instance().addMapLayer(selectedLayer_1_plot) 
                QgsProject.instance().addMapLayer(selectedLayer_2_plot)    
                
                             
                ######### SYMBOLOGY ######
                # SUBSTATIONS
                layer = selectedLayer_1_plot
                idx = layer.dataProvider().fieldNameIndex('RISK (kWh)')
                min_sub_value = layer.minimumValue(idx)
                max_sub_value = layer.maximumValue(idx)
                
                x = (max_sub_value - min_sub_value) / 5
                range_1 = ('Very Low Risk', 0, x + min_sub_value, '#44ce1b')
                range_2 = ('Low Risk', x + min_sub_value , 2*x + min_sub_value, '#bbdb44')
                range_3 = ('Moderate Risk', 2*x + min_sub_value , 3*x + min_sub_value, '#f7e379')
                range_4 = ('High Risk', 3*x + min_sub_value , 4*x + min_sub_value, '#f2a134')
                range_5 = ('Very High Risk', 4*x + min_sub_value, 5*x + min_sub_value, '#e51f1f')
                
                data = (range_1, range_2, range_3, range_4, range_5)
                
                ranges = []
                for label, lower, upper, color in data:
                    symbol = QgsSymbol.defaultSymbol(layer.geometryType())
                    symbol.setSize(2.5)
                    symbol.setColor(QColor(color))                    
                    rng = QgsRendererRange(lower, upper, symbol, label)
                    ranges.append(rng)
                
                expression = 'RISK (kWh)'
                renderer = QgsGraduatedSymbolRenderer(expression, ranges)
                layer.setRenderer(renderer)
                
                selectedLayer_1.commitChanges()
                
                # POWER LINES
                layer_pl = selectedLayer_2_plot
                idx = layer_pl.dataProvider().fieldNameIndex('RISK (kWh)')
                min_line_value = layer_pl.minimumValue(idx)
                max_line_value = layer_pl.maximumValue(idx)
                
                x = (max_line_value - min_line_value) / 5
                range_1 = ('Very Low Risk', min_line_value , x + min_line_value, '#44ce1b')
                range_2 = ('Low Risk', x + min_line_value , 2*x + min_line_value, '#bbdb44')
                range_3 = ('Moderate Risk', 2*x + min_line_value , 3*x + min_line_value, '#f7e379')
                range_4 = ('High Risk', 3*x + min_line_value , 4*x + min_line_value, '#f2a134')
                range_5 = ('Very High Risk', 4*x + min_line_value, 5*x + min_line_value, '#e51f1f')
                
                data_pl = (range_1, range_2, range_3, range_4, range_5)
                
                ranges = []
                for label, lower, upper, color in data_pl:
                    symbol = QgsSymbol.defaultSymbol(layer_pl.geometryType())
                    symbol.setWidth(1)
                    symbol.setColor(QColor(color))
                    rng = QgsRendererRange(lower, upper, symbol, label)
                    ranges.append(rng)
                
                expression = 'RISK (kWh)'
                renderer = QgsGraduatedSymbolRenderer(expression, ranges)
                layer_pl.setRenderer(renderer)
                                             
                selectedLayer_2.commitChanges()
                
                ###### RESILIENCY CALCUALTION ####
                q = 0
                p = 0
                imp = 0
                for a in selectedLayer_1.getFeatures():
                    q = q + a['Total_risk']
                for b in selectedLayer_2.getFeatures():
                    p = p + b['Total_risk']
                
                Energy_risk = q + p
                Resilience = math.ceil(((1 - (Energy_risk/(energy*features_num*hazards_num)))*100)*100)/100
                
                
                ###### DATA TO EXCEL ######                
                
                fieldnames_1 = [field.name() for field in selectedLayer_1.fields()]                               
                fieldnames_2 = [field.name() for field in selectedLayer_2.fields()]
                
                # write header
                line_1 = ','.join(name for name in fieldnames_1) + '\n'
                output_file.write(line_1)
                # write feature attributes
                for f in selectedLayer_1.getFeatures():
                    line_2 = ','.join(str(f[name]) for name in fieldnames_1) + '\n'
                    output_file.write(line_2)                
                
                line_3 = ','.join(name for name in fieldnames_2) + '\n'
                output_file.write(line_3)
                for f in selectedLayer_2.getFeatures():
                    line_4 = ','.join(str(f[name]) for name in fieldnames_2) + '\n'
                    output_file.write(line_4)
                    
            
            self.iface.messageBar().pushMessage("The resilience index of the system is:", str(Resilience) + " %" , level=Qgis.Info, duration=0)
            self.iface.messageBar().pushMessage("Success", "Output file written at " + filename,level=Qgis.Success, duration=3)
            
            