# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HazardIden
                                 A QGIS plugin
 Natural hazards indentification for resiliency analysis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-12-12
        git sha              : $Format:%H$
        copyright            : (C) 2023 by MMP
        email                : montserrat.montala@upc.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.core import QgsProject
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QVariant
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsProject, Qgis, QgsLayerTreeGroup, QgsLayerTreeLayer, QgsField, QgsFields, QgsFeature, QgsVectorLayer, QgsExpression  #modified 15/12/2023

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .Hazards_Identification_dialog import HazardIdenDialog
import os.path


class HazardIden:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'HazardIden_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Hazards Identification')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('HazardIden', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/Hazards_Identification/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'CITCEA Resiliency'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Hazards Identification'),
                action)
            self.iface.removeToolBarIcon(action)
            
    def select_output_file(self):
        filename, _filter = QFileDialog.getSaveFileName(self.dlg, "Select output file ","", '*.csv')
        self.dlg.lineEdit.setText(filename)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = HazardIdenDialog()
        # Fetch the currently loaded layers
        layers = QgsProject.instance().layerTreeRoot().findGroup('System_TBA').children()
        
        #Input Hazard layers
        root = QgsProject.instance().layerTreeRoot().findGroup('Layers_withHazards')
        hazards = QgsProject.instance().layerTreeRoot().findGroup('Layers_withHazards').children()  #added 14/12/2023
        n = 0                                                                                       #added 15/12/2023
        hazards_names = []                                                                          #added 15/12/2023         
        for child in root.children():                                                               #added 15/12/2023
            if isinstance(child, QgsLayerTreeLayer):                                                #added 15/12/2023
                n = n + 1                                                                           #added 15/12/2023
                hazards_names.append(child.name())                                                  #added 15/12/2023
        
                    
        
        # Clear the contents of the comboBox from previous runs
        self.dlg.comboBox.clear()
        self.dlg.comboBox_2.clear()
        # Populate the comboBox with names of all the loaded layers
        self.dlg.comboBox.addItems([layer.name() for layer in layers])
        self.dlg.comboBox_2.addItems([layer.name() for layer in layers])
        self.dlg.pushButton.clicked.connect(self.select_output_file)
        
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            
            selectedLayerIndex_1 = self.dlg.comboBox.currentIndex()
            selectedLayerIndex_2 = self.dlg.comboBox_2.currentIndex()
            
            
            filename = self.dlg.lineEdit.text()
            with open(filename, 'w') as output_file:
                selectedLayerIndex_1 = self.dlg.comboBox.currentIndex()
                selectedLayerIndex_2 = self.dlg.comboBox_2.currentIndex()
                selectedLayer_1 = layers[selectedLayerIndex_1].layer()
                selectedLayer_2 = layers[selectedLayerIndex_2].layer()
                
                # Add attributes from the hazards layers                                                                            #added 15/12/2023
                              
                pr = selectedLayer_1.dataProvider()                                                                                 #added 15/12/2023
                selectedLayer_1.startEditing()                                                                                      #added 15/12/2023
                    
                                             
                for i in list(range(0,len(hazards_names))):                                                                         #added 15/12/2023
                    pr.addAttributes([QgsField(str(hazards_names[i]), QVariant.String)])                                               #added 15/12/2023
                    selectedLayer_1.updateFields()                                                                                  #added 15/12/2023
                    for f in selectedLayer_1.getFeatures():                                                                         #added 18/12/2023
                        f[str(hazards_names[i])] = 'No data yet'                                                                               #added 18/12/2023
                        selectedLayer_1.updateFeature(f)                                                                            #added 18/12/2023
                    
                selectedLayer_1.commitChanges() 
                
                fieldnames_1 = [field.name() for field in selectedLayer_1.fields()]                               
                fieldnames_2 = [field.name() for field in selectedLayer_2.fields()]
                
                # write header
                line_1 = ','.join(name for name in fieldnames_1) + '\n'
                output_file.write(line_1)
                # write feature attributes
                for f in selectedLayer_1.getFeatures():
                    line_2 = ','.join(str(f[name]) for name in fieldnames_1) + '\n'
                    output_file.write(line_2)
                
                
                line_3 = ','.join(name for name in fieldnames_2) + '\n'
                output_file.write(line_3)
                for f in selectedLayer_2.getFeatures():
                    line_4 = ','.join(str(f[name]) for name in fieldnames_2) + '\n'
                    output_file.write(line_4)
            self.iface.messageBar().pushMessage("Success", "Output file written at " + filename,level=Qgis.Success, duration=3)